-- =============================================
-- 社区共享工具租赁系统 数据库结构 (PostgreSQL 16)
-- 约定：主键自增 / 无物理外键 / 状态字段 varchar(注释内为枚举值)
-- =============================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============ system 模块 ============
CREATE TABLE sys_user
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(50)  NOT NULL UNIQUE,
    password    varchar(100) NOT NULL,
    real_name   varchar(50),
    phone       varchar(256),                           -- AES 加密存储
    id_card     varchar(256),                           -- AES 加密存储（展示时脱敏）
    role        varchar(20)  NOT NULL,                  -- RESIDENT 居民 / STAFF 工作人员 / ADMIN 管理员
    status      varchar(20)  NOT NULL DEFAULT 'ACTIVE', -- ACTIVE / DISABLED
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_user IS '用户表';

CREATE TABLE sys_config
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key   varchar(100) NOT NULL UNIQUE,
    config_value varchar(500),
    remark       varchar(200),
    create_time  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_config IS '全局配置表（如默认提醒方式）';

-- ============ tool 模块 ============
CREATE TABLE tool_category
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(20) NOT NULL UNIQUE, -- 编码规则中的类别段 xx
    name        varchar(50) NOT NULL,
    create_time timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE tool_category IS '工具类别表';

CREATE TABLE tool_info
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_code        varchar(30)    NOT NULL UNIQUE,              -- SQ-G-xx-YYYY
    name             varchar(100)   NOT NULL,
    model            varchar(100),                                -- 型号规格
    category_id      bigint         NOT NULL,
    description      text,                                        -- 使用说明
    damage_level     varchar(20)    NOT NULL DEFAULT 'NONE',      -- NONE / LIGHT / MEDIUM / SEVERE
    deposit_amount   numeric(10, 2) NOT NULL DEFAULT 0,           -- 押金
    storage_area     varchar(50),                                 -- 存放区域
    purchase_date    date,                                        -- 采购日期
    supplier         varchar(200),                                -- 供应商信息
    creator_id       bigint,                                      -- 录入人 sys_user.id
    audit_status     varchar(20)    NOT NULL DEFAULT 'PENDING',   -- PENDING 待审核 / APPROVED 已通过 / REJECTED 需修改
    audit_remark     varchar(200),                                -- 审核意见（需修改时填写）
    status           varchar(20)    NOT NULL DEFAULT 'AVAILABLE', -- AVAILABLE / RESERVED / IN_USE / REPAIRING / DISCARDED
    rental_count     int            NOT NULL DEFAULT 0,           -- 租赁次数
    last_repair_time timestamp,
    create_time      timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE tool_info IS '工具信息表';
CREATE INDEX idx_tool_info_category ON tool_info (category_id);
CREATE INDEX idx_tool_info_status ON tool_info (status);

CREATE TABLE tool_image
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id     bigint       NOT NULL,
    url         varchar(500) NOT NULL, -- MinIO 对象地址
    sort        int          NOT NULL DEFAULT 0,
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE tool_image IS '工具图片表';
CREATE INDEX idx_tool_image_tool ON tool_image (tool_id);

CREATE TABLE tool_status_log
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id     bigint      NOT NULL,
    old_status  varchar(20),
    new_status  varchar(20) NOT NULL,
    reason      varchar(200),
    operator_id bigint, -- 操作人 sys_user.id
    create_time timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE tool_status_log IS '工具状态变更日志';
CREATE INDEX idx_tool_status_log_tool ON tool_status_log (tool_id);

-- ============ rental 模块 ============
CREATE TABLE rental_order
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code       varchar(30)    NOT NULL UNIQUE,                 -- 预约单号
    tool_id          bigint         NOT NULL,
    user_id          bigint         NOT NULL,                        -- 租赁人
    pickup_person    varchar(50),                                    -- 取件人（可代取）
    start_time       timestamp      NOT NULL,                        -- 租赁开始
    end_time         timestamp      NOT NULL,                        -- 租赁结束
    deposit_amount   numeric(10, 2) NOT NULL,
    deposit_status   varchar(20)    NOT NULL DEFAULT 'UNPAID',       -- UNPAID / PAID / REFUNDING / REFUNDED
    status           varchar(20)    NOT NULL DEFAULT 'PENDING_PAYMENT', -- PENDING_PAYMENT / RESERVED / PICKED_UP / RETURNED / CANCELLED / OVERDUE
    pickup_time      timestamp,                                      -- 实际取件时间
    return_time      timestamp,                                      -- 实际归还时间（逾期费计算依据）
    accept_result    varchar(20),                                    -- 归还验收 NORMAL 完好 / MINOR_DAMAGED 轻微损坏（无需赔偿） / SEVERE_DAMAGED 严重损坏（需赔偿）
    acceptor_id      bigint,                                         -- 验收人（工作人员）
    overdue_fee      numeric(10, 2) NOT NULL DEFAULT 0,              -- 逾期费用
    compensation_fee numeric(10, 2) NOT NULL DEFAULT 0,              -- 损坏赔偿金额（验收确定，从押金中扣除）
    cancel_reason    varchar(200),
    create_time      timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE rental_order IS '租赁预约/记录表（单据全生命周期）';
CREATE INDEX idx_rental_order_tool ON rental_order (tool_id);
CREATE INDEX idx_rental_order_user ON rental_order (user_id);

CREATE TABLE pay_record
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_code    varchar(30)    NOT NULL UNIQUE,            -- 支付单号（模拟沙箱）
    biz_type    varchar(20)    NOT NULL,                   -- DEPOSIT 押金 / REPAIR_FEE 维修费 / REFUND 退款
    biz_id      bigint         NOT NULL,                   -- 关联业务单 id
    amount      numeric(10, 2) NOT NULL,
    status      varchar(20)    NOT NULL DEFAULT 'SUCCESS', -- PENDING / SUCCESS / FAILED / REFUNDED
    pay_time    timestamp,
    create_time timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE pay_record IS '支付流水表（押金/维修费/退款）';
CREATE INDEX idx_pay_record_biz ON pay_record (biz_type, biz_id);

-- ============ repair 模块 ============
CREATE TABLE repair_order
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_code        varchar(30)  NOT NULL UNIQUE,              -- 报修申请号
    tool_id            bigint       NOT NULL,
    order_id           bigint,                                    -- 关联租赁单（租赁期间报修）
    reporter_id        bigint       NOT NULL,                     -- 报修人
    damage_part        varchar(100) NOT NULL,                     -- 损坏部位
    description        varchar(500) NOT NULL,                     -- 损坏描述
    status             varchar(20)  NOT NULL DEFAULT 'SUBMITTED', -- SUBMITTED / CHECKING 疑似损坏待检测 / CONFIRMED / WAITING_PARTS 待配件 / REPAIRING / FINISHED / ACCEPTED / REJECTED
    handler_id         bigint,                                    -- 维修负责人
    estimated_duration varchar(100),                              -- 维修预计时长（如 3 个工作日）
    repair_fee         numeric(10, 2),                            -- 维修费用
    repair_description varchar(500),                              -- 维修说明
    accept_result      varchar(20),                               -- 修后验收 PASS 合格（恢复可用） / FAIL 不合格（二次维修或报废） / PARTIAL 部分合格（限用）
    reject_reason      varchar(200),                              -- 核验不通过原因
    create_time        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE repair_order IS '损坏报修单';
CREATE INDEX idx_repair_order_tool ON repair_order (tool_id);

CREATE TABLE repair_progress
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_id   bigint       NOT NULL,
    content     varchar(500) NOT NULL, -- 进度说明
    operator_id bigint,                -- 操作人（工作人员）
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE repair_progress IS '维修进度时间线';
CREATE INDEX idx_repair_progress_repair ON repair_progress (repair_id);

CREATE TABLE repair_image
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_id   bigint       NOT NULL,
    url         varchar(500) NOT NULL, -- MinIO 对象地址（图片/视频）
    sort        int          NOT NULL DEFAULT 0,
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE repair_image IS '报修证明材料表（图片/视频）';
CREATE INDEX idx_repair_image_repair ON repair_image (repair_id);

-- ============ message 模块 ============
CREATE TABLE msg_record
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL,                   -- 接收人
    type        varchar(20)  NOT NULL,                   -- DUE_SOON 到期 / OVERDUE 逾期 / REPAIR_DONE 维修完成 / PICKUP 取件
    title       varchar(100) NOT NULL,
    content     varchar(1000),
    channel     varchar(20)  NOT NULL DEFAULT 'IN_APP',  -- IN_APP 站内信 / SMS 短信
    send_status varchar(20)  NOT NULL DEFAULT 'PENDING', -- PENDING / SENT / FAILED
    send_time   timestamp,
    biz_code    varchar(30),                             -- 关联业务单号
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE msg_record IS '消息提醒存档';
CREATE INDEX idx_msg_record_user ON msg_record (user_id);

-- ============ assistant 模块（RAG 知识库） ============
CREATE TABLE kb_document
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name    varchar(200) NOT NULL,
    uploader_id bigint,                                  -- 上传人
    doc_type    varchar(20),                             -- MANUAL 工具手册 / WARNING 安全警示 / RULE 租赁规则
    tool_id     bigint,                                  -- 工具手册归属工具，规则类为空
    file_url    varchar(500) NOT NULL,                   -- MinIO 原文件地址
    status      varchar(20)  NOT NULL DEFAULT 'PENDING', -- PENDING / PROCESSING / READY / FAILED
    chunk_count int          NOT NULL DEFAULT 0,
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE kb_document IS '知识库文档表';
CREATE INDEX idx_kb_document_tool ON kb_document (tool_id);

CREATE TABLE kb_chunk
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint    NOT NULL,
    tool_id     bigint,             -- 命中工具手册片段时可直接关联工具
    content     text      NOT NULL, -- 切片原文（作为回答的来源片段展示）
    embedding   vector(1024),       -- 向量维度 1024，须与 embedding API 输出一致
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE kb_chunk IS '文档切片与向量表';
CREATE INDEX idx_kb_chunk_document ON kb_chunk (document_id);
CREATE INDEX idx_kb_chunk_tool ON kb_chunk (tool_id);
CREATE INDEX idx_kb_chunk_embedding ON kb_chunk USING hnsw (embedding vector_cosine_ops);
